deployment:
  kind: DaemonSet

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

hostNetwork: true

service:
  enabled: true

ports:
  web:
    port: 8000
    exposedPort: 8000
    expose:
      default: true

  websecure:
    port: 8443
    exposedPort: 8443
    expose:
      default: true

  traefik:
    expose:
      default: false

#tlsStore:
#  default:
#    defaultCertificate:
#      secretName: default-tls-cert

ingressClass:
  enabled: true
  #isDefaultClass: true
  name: traefik

#providers:
#  kubernetesIngress:
#    enabled: true
#    publishedService:
#      enabled: true
#  kubernetesCRD:
#    enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
