deployment:
  kind: Deployment
  replicas: 3

service:
  enabled: true
  type: NodePort

ports:
  web:
    nodePort: 8000

  websecure:
    nodePort: 8443

  traefik:
    expose:
      default: false

#tlsStore:
#  default:
#    defaultCertificate:
#      secretName: default-tls-cert

ingressClass:
  enabled: true
  #isDefaultClass: true
  name: traefik

#providers:
#  kubernetesIngress:
#    enabled: true
#    publishedService:
#      enabled: true
#  kubernetesCRD:
#    enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
