expose:
  type: ingress
  tls:
    enable: true
    certSource: none
  ingress:
    hosts:
      core: registry.unixworld.io
  persistentVolumeClaim:
    jobservice:
      jobLog:
        storageClass: "csi-cephfs-sc"
        accessMode: ReadWriteMany
        size: 1Gi
