apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>Helm Test</title></head>
      <body>
        <h1>{{ .Values.message }}</h1>
      </body>
    </html>
