apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
    color: blue
  annotations:
    "lbipam.cilium.io/ips": "{{ .Values.vip }}"
  name: hello-world
  namespace: web-apps
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-nginx
  type: LoadBalancer
